name: create-issue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: create issue
        run: |
          gh issue create \
            --title "Testing" \
            --body "This is a test issue, please ignore."
  
