name: create-issue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
    permissions:
      issues: write

    steps:
      - name: create issue
        run: |
          gh issue create \
            --title "Testing" \
            --body "This is a test issue, please ignore."
  
